src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $book_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBookId(): ?Book
    {
        return $this->book_id;
    }

    public function setBookId(?Book $book_id): self
    {
        $this->book_id = $book_id;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/ReviewType.php
<?php

namespace App\Form;

use App\Entity\Review;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReviewType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description')
            ->add('name')
            ->add('book_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Review::class,
        ]);
    }
}

src/Controller/ReviewController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\Review;
use App\Form\ReviewType;
use App\Form\ReviewTypeWithCurrent;
use App\Repository\ReviewRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/review")
 */
class ReviewController extends AbstractController
{
    /**
     * @Route("/", name="review_index", methods={"GET"})
     */
    public function index(ReviewRepository $reviewRepository): Response
    {
        return $this->render('review/index.html.twig', [
            'reviews' => $reviewRepository->findAll(),

        ]);
    }

    /**
     * @Route("/new", name="review_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $review = new Review();
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($review);
            $entityManager->flush();

            return $this->redirectToRoute('review_index');
        }

        return $this->render('review/new.html.twig', [
            'review' => $review,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/new/{book_id}", name="review_new_book_id", methods={"GET","POST"})
     */
    public function newCommentWithCurrentBook(Request $request, Book $book_id ): Response
    {
        $review = new Review();
        $review->setBookId($book_id);
        $form = $this->createForm(ReviewTypeWithCurrent::class, $review);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($review);
            $entityManager->flush();

            return $this->redirectToRoute('review_index');
        }

        return $this->render('review/new.html.twig', [
            'review' => $review,
            'form' => $form->createView(),
            'book_id' => $book_id
        ]);
    }

    /**
     * @Route("/{id}", name="review_show", methods={"GET"})
     */
    public function show(Review $review): Response
    {
        return $this->render('review/show.html.twig', [
            'review' => $review,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="review_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Review $review): Response
    {
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('review_index');
        }

        return $this->render('review/edit.html.twig', [
            'review' => $review,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="review_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Review $review): Response
    {
        if ($this->isCsrfTokenValid('delete'.$review->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($review);
            $entityManager->flush();
        }

        return $this->redirectToRoute('review_index');
    }
}

templates/review/_delete_form.html.twig
<form method="post" action="{{ path('review_delete', {'id': review.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ review.id) }}">
    <button class="btn">Delete</button>
</form>

templates/review/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Review{% endblock %}

{% block body %}
    <h1>Edit Review</h1>

    {{ include('review/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('review_index') }}">back to list</a>

    {{ include('review/_delete_form.html.twig') }}
{% endblock %}

templates/review/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review index{% endblock %}

{% block body %}
    <h1>Review index</h1>
    <div class="row">
        <div class="col-xl">
            <table class="table table-striped">
                <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Description</th>
                    <th>Name</th>
                    <th>Book</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for review in reviews %}
                    <tr>
                        <td>{{ review.id }}</td>
                        <td>{{ review.description }}</td>
                        <td>{{ review.name }}</td>
                        <td>{{ review.bookId.title }}</td>
                        <td>
                            <a class="btn btn-dark" href="{{ path('review_show', {'id': review.id}) }}">show</a>
                            <a class="btn btn-info" href="{{ path('review_edit', {'id': review.id}) }}">edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
    <div class="row">
        <div class="col-xl">
            <a class="btn btn-info mb-5 mt-3 " href="{{ path('review_new') }}">Create new</a>
        </div>

    </div>

{% endblock %}

templates/review/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Review{% endblock %}

{% block body %}
    <h1>Create new Review</h1>

    {% if book_id is defined %}
        <h3>{{ book_id.title }}</h3>
    {% endif %}

    {{ include('review/_form.html.twig') }}

    <a class="btn btn-primary mt-3 mb-5" href="{{ path('review_index') }}">Back</a>
{% endblock %}

templates/review/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review{% endblock %}

{% block body %}
    <h1>Review</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ review.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ review.description }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ review.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('review_index') }}">back to list</a>

    <a href="{{ path('review_edit', {'id': review.id}) }}">edit</a>

    {{ include('review/_delete_form.html.twig') }}
{% endblock %}